### Create profle
POST localhost:8081/api/v1/profile
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE3MjI4NDIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE4MDkyNDIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.HZ_HrWnqS41WJV8TfWfhUk-9Q1KmWKcuIf4-hwPR4a3o-MztksgE6vXoJYuWPdWJ-CpJfP6E6z4FiLP_XuNRRw

{
  "name": "Alish",
  "surname": "Aliyev",
  "email": "alish@mail.ru",
  "phone": "1213",
  "password": "123456",
  "role": "MODERATOR"
}

